
#define WACCGL_KEY_ARROW_UP key(-32, 72)
#define WACCGL_KEY_ARROW_DOWN key(-32, 80)
#define WACCGL_KEY_ARROW_LEFT key(-32, 75)
#define WACCGL_KEY_ARROW_RIGHT key(-32, 77)
#define WACCGL_KEY_ENTER key(13)
#define WACCGL_KEY_TAB key(-32, 9)
#define WACCGL_KEY_BACKSPACE key(-32, 8)
#define WACCGL_KEY_ESCAPE key(27)
#define WACCGL_KEY_DELETE key(-32, 83)


#define WACCGL_KEY_FOCUS_PREV1 WACCGL_KEY_ARROW_LEFT
#define WACCGL_KEY_FOCUS_PREV2 key(-32, 46)
#define WACCGL_KEY_FOCUS_NEXT1 WACCGL_KEY_ARROW_RIGHT
#define WACCGL_KEY_FOCUS_NEXT2 key(-32, 47)
#define WACCGL_KEY_ACTION WACCGL_KEY_ENTER
#define WACCGL_KEY_SELECT_NEXT WACCGL_KEY_ARROW_UP
#define WACCGL_KEY_SELECT_PREV WACCGL_KEY_ARROW_DOWN
#define WACCGL_KEY_SCROLL_UP WACCGL_KEY_ARROW_UP
#define WACCGL_KEY_SCROLL_DOWN WACCGL_KEY_ARROW_DOWN
#define WACCGL_KEY_TEXT_NEXT_LINE WACCGL_KEY_ARROW_DOWN
#define WACCGL_KEY_TEXT_PREV_LINE WACCGL_KEY_ARROW_UP
#define WACCGL_KEY_TEXT_NEXT_COLUMN WACCGL_KEY_ARROW_RIGHT
#define WACCGL_KEY_TEXT_PREV_COLUMN WACCGL_KEY_ARROW_LEFT
#define WACCGL_KEY_TEXT_DELETE WACCGL_KEY_DELETE
#define WACCGL_KEY_TEXT_BACKSPACE WACCGL_KEY_BACKSPACE
#define WACCGL_KEY_TEXT_NEW_LINE WACCGL_KEY_ENTER
#define WACCGL_KEY_TEXT_TABULATION WACCGL_KEY_TAB
